services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
