services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
