services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - /home/mvolkman/data/web:/var/www/html
    networks:
      - inception_network
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME} # Pass DOMAIN_NAME to the container
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
      - /home/mvolkman/data/web:/var/www/html
    networks:
      - inception_network
    secrets:
      - db_name
      - db_user
      - db_pass
      - db_root_pass
      - admin_user
      - admin_pass
      - admin_email
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}  # Reference the variable from .env
    restart: always
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /home/mvolkman/data/db:/var/lib/mysql
    secrets:
      - db_name
      - db_user
      - db_pass
      - db_root_pass
    networks:
      - inception_network
  ftp:
    build: requirements/bonus/ftp/.
    container_name: ftp
    depends_on:
      - wordpress
    secrets:
      - ftp_user
      - ftp_pass
    volumes:
      - /home/mvolkman/data/web:/var/www/html
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception_network
    restart: always

networks:
  inception_network:

secrets:
  db_name:
    file: ../secrets/db_name.txt
  db_user:
    file: ../secrets/db_user.txt
  db_pass:
    file: ../secrets/db_pass.txt
  db_root_pass:
    file: ../secrets/db_root_pass.txt
  admin_user:
    file: ../secrets/admin_user.txt
  admin_pass:
    file: ../secrets/admin_pass.txt
  admin_email:
    file: ../secrets/admin_email.txt
  ftp_user:
    file: ../secrets/ftp_user.txt
  ftp_pass:
    file: ../secrets/ftp_pass.txt
